# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'


steps:
- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: 'restore'
    projects: '**/WebApp.csproj'

- task: DotNetCoreCLI@2
  displayName: Apply testing
  inputs:
    command: 'build'
    projects: '**/WebApp.csproj'
    arguments: '--configuration $(buildconfiguration)'



- task: DotNetCoreCLI@2
  displayName: create webpackage.zip
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildconfiguration) --output $(build.artifactstagingdirectory)'


- task: PublishBuildArtifacts@1
  displayName: copy to artifacts
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
